using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using System;

public enum CountriesEnum
{
    Afrique_du_Sud,
    Afghanistan,
    ainte_Lucie,
    Albanie,
    Algérie,
    Allemagne,
    Andorre,
    Angola,
    Antigua_et_Barbuda,
    Arabie_saoudite,
    Argentine,
    Arménie,
    Australie,
    Autriche,
    Azerbaïdjan,
    Bahamas,
    Bahreïn,
    Bangladesh,
    Barbade,
    Belgique,
    Belize,
    Bénin,
    Bhoutan,
    Biélorussie,
    Birmanie,
    Bolivie,
    Bosnie_Herzégovine,
    Botswana,
    Brésil,
    Brunei,
    Bulgarie,
    Burkina,
    Burundi,
    Cambodge,
    Cameroun,
    Canada,
    Cap_Vert,
    Chili,
    Chine,
    Chypre,
    Colombie,
    Comores,
    Congo,
    Corée_du_Nord,
    Corée_du_Sud,
    Costa_Rica,
    Côte_d_Ivoire,
    Croatie,
    Cuba,
    Danemark,
    Djibouti,
    Dominique,
    Égypte,
    Émirats_arabes_unis,
    Équateur,
    Érythrée,
    Espagne,
    Estonie,
    États_Unis,
    Éthiopie,
    Fidji,
    Finlande,
    France,
    Gabon,
    Gambie,
    Géorgie,
    Ghana,
    Grèce,
    Grenade,
    Guatemala,
    Guinée,
    Guinée_Bissau,
    Guinée_équatoriale,
    Guyana,
    Haïti,
    Honduras,
    Hongrie,
    Inde,
    Indonésie,
    Irak,
    Iran,
    Irlande,
    Islande,
    Israël,
    Italie,
    Jamaïque,
    Japon,
    Jordanie,
    Kazakhstan,
    Kenya,
    Kirghizistan,
    Kiribati,
    Koweït,
    Laos,
    Lesotho,
    Lettonie,
    Liban,
    Libéria,
    Libye,
    Liechtenstein,
    Lituanie,
    Luxembourg,
    Madagascar,
    Malaisie,
    Malawi,
    Maldives,
    Mali,
    Malte,
    Maroc,
    Marshall,
    Maurice,
    Mauritanie,
    Mexique,
    Micronésie,
    Moldavie,
    Monaco,
    Mongolie,
    Monténégro,
    Mozambique,
    Namibie,
    Nauru,
    Népal,
    Nicaragua,
    Niger,
    Nigeria,
    Norvège,
    Nouvelle_Zélande,
    Oman,
    Ouganda,
    Ouzbékistan,
    Pakistan,
    Palaos,
    Palestine,
    Panama,
    Papouasie_Nouvelle_Guinée,
    Paraguay,
    Pays_Bas,
    Pérou,
    Philippines,
    Pologne,
    Porto_Rico,
    Portugal,
    Qatar,
    République_centrafricaine,
    République_de_Macédoine,
    République_démocratique_du_congo,
    République_dominicaine,
    République_tchèque,
    Roumanie,
    Royaume_Uni,
    Russie,
    Rwanda,
    Saint_Christophe_et_Niévès,
    Saint_Marin,
    Saint_Vincent_et_les_Grenadines,
    Salomon,
    Salvador,
    Samoa,
    Sao_Tomé_et_Principe,
    Sénégal,
    Serbie,
    Seychelles,
    Sierra_Leone,
    Singapour,
    Slovaquie,
    Slovénie,
    Somalie,
    Soudan,
    Sri_Lanka,
    Sud_Soudan,
    Suède,
    Suisse,
    Suriname,
    Swaziland,
    Syrie,
    Tadjikistan,
    Taïwan,
    Tanzanie,
    Tchad,
    Thaïlande,
    Timor_oriental,
    Togo,
    Tonga,
    Trinité_et_Tobago,
    Tunisie,
    Turkménistan,
    Turquie,
    Tuvalu,
    Ukraine,
    Uruguay,
    Vanuatu,
    Vatican,
    Venezuela,
    Viêt_Nam,
    Yémen,
    Zambie,
    Zimbabwe,
    Other
    
}
public class Countries : MonoBehaviour
{
    public Dropdown countryList;
    public Text selectedName;

    private void Start()
    {
        setCountries();
    }

    public void setCountries()
    {
        string[] enumNames = Enum.GetNames(typeof(CountriesEnum));
        List<string> names = new List<string>(enumNames);

        countryList.AddOptions(names);
    }

    public void Dropdown_IndesChanges (int index)
    {
        if (index == 0)
        {
            selectedName.color = Color.red;
        }

        else
        {
            selectedName.color = Color.white;
        }
    }
}
